language: swift
os: osx
osx_image: xcode9.4
rvm: 2.4.2
cache:
  - bundler
  - cocoapods

before_install:
  - bundle install --deployment
  - bundle exec pod repo update

install:
  - bundle exec fastlane pods

script:
  - bundle exec fastlane test

before_deploy:
  - rvm $TRAVIS_RUBY_VERSION do bundle exec pod repo add wuakitv git@github.com:wuakitv/ios-specs.git

deploy:
  skip_cleanup: true
  provider: script
  script: rvm $TRAVIS_RUBY_VERSION do bundle exec fastlane publish
  on:
    branch: master

branches:
  only:
    - develop
    - /^feature\/.*/
    - /^release\/.*/
    - /^hotfix\/.*/
    - master
